### ISSUE TITLE
Trash not working after 3.0.0 Update (Win7)

### ISSUE THREAD

**Issue by mscarchilli** [sindresorhus/trash#39]
After updating to v 3.1.1 (Win7), trash is no longer working. Before the update it worked perfect when I had v2.0.0. 

I get the following when trying to trash anything now.

```
sh.exe": /local/trash: No such file or directory
```

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/trash/releases/tag/v3.0.0

**Comment by mscarchilli** [comment]
I tried that already and got the following:

```
C:\Program Files (x86)\Git\local\node_modules\trash-cli\cli.js:4
const updateNotifier = require('update-notifier');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by sindresorhus** [comment]
Upgrade Node.js. Node.js 4 is required.

**Comment by mscarchilli** [comment]
I'll give that a try. Thanks for the quick responses!

**Comment by mscarchilli** [comment]
Updated to Node v4.2.1

```
 $ trash test.txt
Error: Command failed: C:\Program Files (x86)\Git\local\node_modules\trash-cli\node_modules\trash\lib\win-trash.exe C:\xampp\htdocs\Projects\test.txt

    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

**Comment by sindresorhus** [comment]
Works fine for me on Windows 10. I don't have Windows 7 to test on. Maybe make sure the install was not corrupted, and try reinstalling just in case (make sure to look at the install output).

**Comment by kevva** [comment]
I can confirm it's not working on Windows 7.

**Comment by mscarchilli** [comment]
I completely uninstalled Node this time and reinstalled v4.2.1 (x64). No problems with that install. Then installed trash-cli v1.1.0

Intalled trash-cli output:
```
 $ npm install --global trash-cli
C:\Program Files (x86)\Git\local\trash -> C:\Program Files (x86)\Git\local\node_modules\trash-cli\cli.js
trash-cli@1.1.0 C:\Program Files (x86)\Git\local\node_modules\trash-cli
├── meow@3.4.2 (trim-newlines@1.0.0, object-assign@4.0.1, loud-rejection@1.0.0, minimist@1.2.0, camelcase-keys@1.0.0, redent@1.0.0, read-pkg-up@1.0.1, normalize-package-data@2.3.4)
├── update-notifier@0.5.0 (is-npm@1.0.0, string-length@1.0.1, chalk@1.1.1, semver-diff@2.0.0, repeating@1.1.3, configstore@1.2.1, latest-version@1.0.1)
└── trash@3.1.1 (escape-string-applescript@1.0.0, path-exists@2.0.0, run-applescript@2.0.0, pify@2.2.0, uuid@2.0.1, pinkie-promise@1.0.0, xdg-trashdir@2.0.0, fs-extra@0.24.0)
```

Tried to trash my test file. Output:
```
 $ trash test.txt
Error: Command failed: C:\Program Files (x86)\Git\local\node_modules\trash-cli\node_modules\trash\lib\win-trash.exe c:\xampp\htdocs\Projects\test.txt

    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

If you need me to try some other things just let me know.

**Comment by kevva** [comment]
It's not related to node. The binary simply doesn't work on Windows 7.

**Comment by sindresorhus** [comment]
Should be fixed now. Just reinstall. `$ npm install -gf trash-cli`

**Comment by kevva** [comment]
:tada:

**Comment by mscarchilli** [comment]
Confirmed. Thank you!
