### ISSUE TITLE
Error: spawn EACCES

### ISSUE THREAD

**Issue by boeserwolf** [sindresorhus/trash#62]
I'm getting following error on macOS 10.12.6:
```
Error: spawn EACCES
    at _errnoException (util.js:1041:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at exports.spawn (child_process.js:493:9)
    at exports.execFile (child_process.js:208:15)
    at X/nodejs/myapp/node_modules/pify/index.js:29:7
    at Promise (<anonymous>)
    at X/nodejs/myapp/node_modules/pify/index.js:12:10
    at ret (X/nodejs/myapp/node_modules/pify/index.js:56:34)
    at module.exports.paths (X/nodejs/myapp/node_modules/trash/lib/macos.js:38:23)
    at module.exports.iterable (X/nodejs/myapp/node_modules/trash/index.js:20:25) code: 'EACCES', errno: 'EACCES', syscall: 'spawn' }
```
I could solve the issue by setting the execute bit on `trash/lib/macos-trash` like so:
```
chmod +x ./node_modules/trash/lib/macos-trash
```
Node version: 8.4.0
npm version: 5.4.0

**Comment by sindresorhus** [comment]
See https://github.com/npm/npm/issues/18324. Keeping this open until that is resolved.

**Comment by boeserwolf** [comment]
https://github.com/npm/npm/releases/tag/v5.4.1
> This is a very small bug fix release to fix a problem where permissions on installed binaries were being set incorrectly.
